
import javax.swing.UIManager;
import javax.swing.*;
import java.awt.*;
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANKIT
 */
public class GraphPlotting extends javax.swing.JFrame {

        double Xmin=-10;
        double Xmax=10;
        double Ymin=-10;
        double Ymax=10;
        int x = 0;
        int aa = 0;
    /**
     * Creates new form GraphPlotting
     */
    public GraphPlotting() {
        
        
        initComponents();
        setType(true);        
        //setCenterScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btne = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btncosec = new javax.swing.JButton();
        btnsec = new javax.swing.JButton();
        btncot = new javax.swing.JButton();
        btnplot = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        GraphPanel = new javax.swing.JPanel();
        graph_screen = new javax.swing.JPanel();
        btnrb = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        display1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        btnlb = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnallclr = new javax.swing.JButton();
        btnmult = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnabs = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnroot = new javax.swing.JButton();
        btnpi = new javax.swing.JButton();
        btnpow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(new javax.swing.border.MatteBorder(null));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btne.setBackground(new java.awt.Color(51, 51, 51));
        btne.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btne.setForeground(new java.awt.Color(255, 255, 255));
        btne.setText("e");
        btne.setBorder(new javax.swing.border.MatteBorder(null));
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        btnsin.setBackground(new java.awt.Color(255, 204, 0));
        btnsin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsin.setForeground(new java.awt.Color(255, 255, 255));
        btnsin.setText("Sin");
        btnsin.setBorder(new javax.swing.border.MatteBorder(null));
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });

        btncos.setBackground(new java.awt.Color(255, 204, 0));
        btncos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btncos.setForeground(new java.awt.Color(255, 255, 255));
        btncos.setText("Cos");
        btncos.setBorder(new javax.swing.border.MatteBorder(null));
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });

        btntan.setBackground(new java.awt.Color(255, 204, 0));
        btntan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btntan.setForeground(new java.awt.Color(255, 255, 255));
        btntan.setText("Tan");
        btntan.setBorder(new javax.swing.border.MatteBorder(null));
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });

        btnlog.setBackground(new java.awt.Color(255, 204, 0));
        btnlog.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnlog.setForeground(new java.awt.Color(255, 255, 255));
        btnlog.setText("Log");
        btnlog.setBorder(new javax.swing.border.MatteBorder(null));
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        btncosec.setBackground(new java.awt.Color(255, 204, 0));
        btncosec.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btncosec.setForeground(new java.awt.Color(255, 255, 255));
        btncosec.setText("Cosec");
        btncosec.setBorder(new javax.swing.border.MatteBorder(null));
        btncosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosecActionPerformed(evt);
            }
        });

        btnsec.setBackground(new java.awt.Color(255, 204, 0));
        btnsec.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsec.setForeground(new java.awt.Color(255, 255, 255));
        btnsec.setText("Sec");
        btnsec.setBorder(new javax.swing.border.MatteBorder(null));
        btnsec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecActionPerformed(evt);
            }
        });

        btncot.setBackground(new java.awt.Color(255, 204, 0));
        btncot.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btncot.setForeground(new java.awt.Color(255, 255, 255));
        btncot.setText("Cot");
        btncot.setBorder(new javax.swing.border.MatteBorder(null));
        btncot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncotActionPerformed(evt);
            }
        });

        btnplot.setBackground(new java.awt.Color(0, 255, 0));
        btnplot.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnplot.setForeground(new java.awt.Color(255, 255, 255));
        btnplot.setText("GRAPH");
        btnplot.setBorder(new javax.swing.border.MatteBorder(null));
        btnplot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplotActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(255, 204, 0));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("+");
        btnadd.setBorder(new javax.swing.border.MatteBorder(null));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsub.setBackground(new java.awt.Color(255, 204, 0));
        btnsub.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsub.setForeground(new java.awt.Color(255, 255, 255));
        btnsub.setText("-");
        btnsub.setBorder(new javax.swing.border.MatteBorder(null));
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        GraphPanel.setBackground(new java.awt.Color(255, 204, 0));
        GraphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Graph"));
        GraphPanel.setPreferredSize(new java.awt.Dimension(356, 356));

        graph_screen.setBackground(new java.awt.Color(255, 255, 255));
        graph_screen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        graph_screen.setToolTipText("");
        graph_screen.setPreferredSize(new java.awt.Dimension(392, 392));
        graph_screen.setRequestFocusEnabled(false);
        graph_screen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                graph_screenMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                graph_screenMouseMoved(evt);
            }
        });
        graph_screen.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                graph_screenMouseWheelMoved(evt);
            }
        });
        graph_screen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                graph_screenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                graph_screenMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout graph_screenLayout = new javax.swing.GroupLayout(graph_screen);
        graph_screen.setLayout(graph_screenLayout);
        graph_screenLayout.setHorizontalGroup(
            graph_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        graph_screenLayout.setVerticalGroup(
            graph_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
        GraphPanel.setLayout(GraphPanelLayout);
        GraphPanelLayout.setHorizontalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graph_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        GraphPanelLayout.setVerticalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelLayout.createSequentialGroup()
                .addComponent(graph_screen, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnrb.setBackground(new java.awt.Color(255, 204, 0));
        btnrb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnrb.setForeground(new java.awt.Color(255, 255, 255));
        btnrb.setText(")");
        btnrb.setBorder(new javax.swing.border.MatteBorder(null));
        btnrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrbActionPerformed(evt);
            }
        });

        btn.setBackground(new java.awt.Color(51, 51, 51));
        btn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("0");
        btn.setBorder(new javax.swing.border.MatteBorder(null));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(new javax.swing.border.MatteBorder(null));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(new javax.swing.border.MatteBorder(null));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(new javax.swing.border.MatteBorder(null));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(new javax.swing.border.MatteBorder(null));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(new javax.swing.border.MatteBorder(null));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(new javax.swing.border.MatteBorder(null));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        display1.setBackground(new java.awt.Color(0, 0, 0));
        display1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        display1.setForeground(new java.awt.Color(204, 204, 255));
        display1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display1ActionPerformed(evt);
            }
        });
        display1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                display1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("f(x)=");

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(new javax.swing.border.MatteBorder(null));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnlb.setBackground(new java.awt.Color(255, 204, 0));
        btnlb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnlb.setForeground(new java.awt.Color(255, 255, 255));
        btnlb.setText("(");
        btnlb.setBorder(new javax.swing.border.MatteBorder(null));
        btnlb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlbActionPerformed(evt);
            }
        });

        btndel.setBackground(new java.awt.Color(51, 51, 51));
        btndel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 255, 255));
        btndel.setText("DEL");
        btndel.setBorder(new javax.swing.border.MatteBorder(null));
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnallclr.setBackground(new java.awt.Color(51, 51, 51));
        btnallclr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnallclr.setForeground(new java.awt.Color(255, 255, 255));
        btnallclr.setText("CLEAR");
        btnallclr.setBorder(new javax.swing.border.MatteBorder(null));
        btnallclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallclrActionPerformed(evt);
            }
        });

        btnmult.setBackground(new java.awt.Color(255, 204, 0));
        btnmult.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnmult.setForeground(new java.awt.Color(255, 255, 255));
        btnmult.setText("*");
        btnmult.setBorder(new javax.swing.border.MatteBorder(null));
        btnmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultActionPerformed(evt);
            }
        });

        btndiv.setBackground(new java.awt.Color(255, 204, 0));
        btndiv.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndiv.setForeground(new java.awt.Color(255, 255, 255));
        btndiv.setText("/");
        btndiv.setBorder(new javax.swing.border.MatteBorder(null));
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(new javax.swing.border.MatteBorder(null));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btndot.setBackground(new java.awt.Color(51, 51, 51));
        btndot.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndot.setForeground(new java.awt.Color(255, 255, 255));
        btndot.setText(".");
        btndot.setBorder(new javax.swing.border.MatteBorder(null));
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });

        btnabs.setBackground(new java.awt.Color(255, 204, 0));
        btnabs.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnabs.setForeground(new java.awt.Color(255, 255, 255));
        btnabs.setText("abs");
        btnabs.setBorder(new javax.swing.border.MatteBorder(null));
        btnabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabsActionPerformed(evt);
            }
        });

        btnx.setBackground(new java.awt.Color(255, 204, 0));
        btnx.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnx.setForeground(new java.awt.Color(255, 255, 255));
        btnx.setText("x");
        btnx.setBorder(new javax.swing.border.MatteBorder(null));
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });

        btnroot.setBackground(new java.awt.Color(255, 204, 0));
        btnroot.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnroot.setForeground(new java.awt.Color(255, 255, 255));
        btnroot.setText("√");
        btnroot.setBorder(new javax.swing.border.MatteBorder(null));
        btnroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrootActionPerformed(evt);
            }
        });

        btnpi.setBackground(new java.awt.Color(255, 204, 0));
        btnpi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnpi.setForeground(new java.awt.Color(255, 255, 255));
        btnpi.setText("pi");
        btnpi.setBorder(new javax.swing.border.MatteBorder(null));
        btnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpiActionPerformed(evt);
            }
        });

        btnpow.setBackground(new java.awt.Color(255, 204, 0));
        btnpow.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnpow.setForeground(new java.awt.Color(255, 255, 255));
        btnpow.setText("^");
        btnpow.setBorder(new javax.swing.border.MatteBorder(null));
        btnpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(GraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btndot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnallclr, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnlb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnrb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnplot, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnabs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(btnpow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btntan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btndiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnmult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnpi, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btncos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnsec, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncosec, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnallclr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncosec, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnroot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsec, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnabs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnplot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 43, Short.MAX_VALUE))
            .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Graph Plotting");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(610, 0, 240, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chart.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(960, 0, 70, 50);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-menu-30.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 0, 60, 50);

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(">> Simple Calculator");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(">> Scientific Calculator");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(">> Graph Plotting");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(">> History");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(">> Exit");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Project by : Ankit Kaushal");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("& Ankit Kumar Singh");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel15)
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void display1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
    display1.setText(display1.getText()+"3"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlbActionPerformed
    display1.setText(display1.getText()+"(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlbActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
    String b=null;
    if(display1.getText().length()>0){
        StringBuilder strB= new StringBuilder(display1.getText());
        strB.deleteCharAt(display1.getText().length()-1);
        b=strB.toString();
        display1.setText(b);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelActionPerformed

    private void btnallclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallclrActionPerformed
    clear();        
    plot();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnallclrActionPerformed

    private void btnmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultActionPerformed
    display1.setText(display1.getText()+"*"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmultActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
    display1.setText(display1.getText()+"/"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btndivActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
    display1.setText(display1.getText()+"+"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
    display1.setText(display1.getText()+"-"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubActionPerformed

    private void btnrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrbActionPerformed
    display1.setText(display1.getText()+")");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrbActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
    display1.setText(display1.getText()+"8"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
    display1.setText(display1.getText()+"9"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
    display1.setText(display1.getText()+"5"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
    display1.setText(display1.getText()+"6"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
    display1.setText(display1.getText()+".");
        // TODO add your handling code here:
    }//GEN-LAST:event_btndotActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
    display1.setText(display1.getText()+"2"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
    display1.setText(display1.getText()+"e");
        // TODO add your handling code here:
    }//GEN-LAST:event_btneActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
    display1.setText(display1.getText()+"sin(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsinActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
    display1.setText(display1.getText()+"cos(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btncosActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
    display1.setText(display1.getText()+"tan(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btntanActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
    display1.setText(display1.getText()+"log(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrootActionPerformed
    display1.setText(display1.getText()+"√(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrootActionPerformed

    private void btnpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpowActionPerformed
    display1.setText(display1.getText()+"^");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpowActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
    display1.setText(display1.getText()+"x");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxActionPerformed

    private void btnplotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplotActionPerformed
    if(display1.getText().length()==0){
            clear();
            plot();
        }
        else{
            plot();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnplotActionPerformed

    private void btnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpiActionPerformed
    display1.setText(display1.getText()+"π");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpiActionPerformed

    private void graph_screenMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_graph_screenMouseWheelMoved
        zoom(evt);
    }//GEN-LAST:event_graph_screenMouseWheelMoved

    private void graph_screenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph_screenMouseReleased
        isTranslating=false;
    }//GEN-LAST:event_graph_screenMouseReleased

    private void graph_screenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph_screenMousePressed
        isTranslating=true;
        x1=evt.getX();
        y1=evt.getY();
        xminimumClicked=Xmin;
        xmaximumClicked=Xmax;
        yminimumClicked=Ymin;
        ymaximumClicked=Ymax;
    }//GEN-LAST:event_graph_screenMousePressed

    private void graph_screenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph_screenMouseDragged
        translateGraph(evt);
    }//GEN-LAST:event_graph_screenMouseDragged

    private void graph_screenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph_screenMouseMoved
        drawCoordinates(evt);
    }//GEN-LAST:event_graph_screenMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void display1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_display1KeyReleased
    checkExpression();
    saveExpression();
        // TODO add your handling code here:
    }//GEN-LAST:event_display1KeyReleased

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
    display1.setText(display1.getText()+"7");   
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
    display1.setText(display1.getText()+"4"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
    display1.setText(display1.getText()+"1"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
    display1.setText(display1.getText()+"0"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActionPerformed

    private void btncosecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosecActionPerformed
    display1.setText(display1.getText()+"csc(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btncosecActionPerformed

    private void btnsecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecActionPerformed
    display1.setText(display1.getText()+"sec(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsecActionPerformed

    private void btncotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncotActionPerformed
    display1.setText(display1.getText()+"cot(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btncotActionPerformed

    private void btnabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabsActionPerformed
    display1.setText(display1.getText()+"abs(");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnabsActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new GeneralCalculation().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        labelmenucolor(jLabel2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        resetlabelmenucolor(jLabel2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new ScientificCalculation().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        labelmenucolor(jLabel3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        resetlabelmenucolor(jLabel3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new GraphPlotting().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        labelmenucolor(jLabel4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        resetlabelmenucolor(jLabel4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new History().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        labelmenucolor(jLabel5);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        resetlabelmenucolor(jLabel5);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        labelmenucolor(jLabel9);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        resetlabelmenucolor(jLabel9);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if ( x == 210 ) {
            jPanel4.setSize(210, 440);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {

                        for ( int i = 210; i >= 0; i--){
                            Thread.sleep(1);
                            jPanel4.setSize(i, 440);

                            aa++;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        } else if( x == 0 ){
            jPanel4.setSize(x, 440);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            jPanel4.setSize(i, 440);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 210;
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        labelcolor(jLabel6);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        resetlabelcolor(jLabel6);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void setType(boolean graphing) {
        if(!graphing) {
            GraphPanel.setVisible(false);
            //ControlPanel.setVisible(false);
            //setSize(415,465);
        }else{
            GraphPanel.setVisible(true);
            //ControlPanel.setVisible(true);
            //setSize(1250,500);            
        }
        //setCenterScreen();
    }
    //Center on the screen
    private void setCenterScreen(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int locX = dim.width/2 - this.getWidth()/2;
        int locY = dim.height/2 - this.getHeight()/2;
        this.setLocation(locX,locY);
    }
    private void setZoomType(double magnitude, char zoomType)
    {
        //zoomType
        //+ = zoom in
        //- is zoom out
        //s is standard
        //t is trigonometric
        //# is statistic
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
  
        switch(zoomType)
        {
            case '+':
                xMinimum/=magnitude;
                xMaximum/=magnitude;
                yMinimum/=magnitude;
                yMaximum/=magnitude;
                break;
            case '-':
                xMinimum*=magnitude;
                xMaximum*=magnitude;
                yMinimum*=magnitude;
                yMaximum*=magnitude;
                break;
            case 's':
                xMinimum=-10;
                xMaximum=10;
                yMinimum=-10;
                yMaximum=10;
                break;
            case 't':
                xMinimum=Math.PI*-2;
                xMaximum=Math.PI*2;
                yMinimum=-2;
                yMaximum=2;
                break;
            case '#':
                xMinimum=0;
                xMaximum=10;
                yMinimum=0;
                yMaximum=10;
                break;
            default:
                JOptionPane.showMessageDialog(null,"Error occured while attempting to zoom");
        }
        
        //write to bounds text fields
        DecimalFormat DForm = new DecimalFormat("#.##");
        xMinimum=Double.valueOf(DForm.format(xMinimum));
        xMaximum=Double.valueOf(DForm.format(xMaximum));
        yMinimum=Double.valueOf(DForm.format(yMinimum));
        yMaximum=Double.valueOf(DForm.format(yMaximum));
        
        //graph with new window bounds
        plot();
    }
    
    private String getExpression()
    {
        return display1.getText();
    }

    private String getSelectedExpression()
    {
        String result="fx";
        return result;
    }

    private String getCertainExpression(int exp)
    {
        String result="";
        switch(exp+1)
        {
            case 1:
                result=fx;
                break;
            case 2:
                result=gx;
                break;
            case 3:
                result=hx;
                break;
            case 4:
                result=ix;
                break;
            case 5:
                result=jx;
                break;
            case 6:
                result=kx;
                break;
            case 7:
                result=lx;
                break;
        }
        return result;
    }

    private String getSelectedOption()
    {
        String result="f(x)";
        
        return result;
    }

    private void saveExpression()
    {
        fx=getExpression();
                
    }

    private void graphExpression(String someExpression, Color c)
    {
        setColors(Color.red,Color.blue,Color.green,Color.orange,Color.cyan,Color.magenta,Color.pink);
        fx=getExpression();
        
        //Set drawing parameters
        
        BasicStroke graphStroke=new BasicStroke(graphWidth,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND);
        Graphics2D graphics = (Graphics2D) graph_screen.getGraphics();        
        double y;double x;int length=graph_screen.getWidth();int Y;String parsedY;               
        graphics.setColor(c);
        graphics.setStroke(graphStroke);
        int[][] Points = new int[length+1][2];
        xMinimum=Xmin;
        xMaximum=Xmax;
        
        //Get all the points on the line into an array
        
        for (int i=0;i<=length;)
        {
            x=((1.0*i/length)*(xMaximum-xMinimum))+xMinimum;
            parsedY=expression.solve(someExpression,x);
            if (parsedY.equals("Error")==false)
            {
                y=Double.parseDouble(parsedY);            
                Y=getY(y);
                Points[i][0]=i;
                Points[i][1]=Y;
            }
            i++;
        }
        //Draw all the points
        for (int i=3;i<Points.length;i+=1)
        {
            if(Points[i][0]-Points[i-1][0]==1&&Math.abs(Points[i][1]-Points[i-1][1])<graph_screen.getHeight()*3)
            {
                graphics.drawLine(Points[i-1][0],Points[i-1][1],Points[i][0],Points[i][1]);
                if(!drawInstantly && !isZooming && !isTranslating) {
                    try {
                        Thread.sleep(10);
                    } catch (Exception e) {}
                }
            }
        }                     
    }

    private void clearGraph()
    {
        int length=graph_screen.getWidth();
        Graphics2D graphics = (Graphics2D) graph_screen.getGraphics();
        graphics.setColor(graphColor);
        graphics.fillRect(0,0,length,graph_screen.getHeight());
    }

    //get Y on the screen based on y-value of graph
    private int getY(double y)
    {
        int height=graph_screen.getHeight();int result;
        yMinimum=Ymin;
        yMaximum=Ymax;
        result=(int)Math.round(height-(((y-yMinimum)/(yMaximum-yMinimum))*height));
        return result;
    }

    private void drawAxis()
    {
        if (Axis)
        {
        int length=graph_screen.getWidth();
        int height=graph_screen.getHeight();
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
        BasicStroke Stroke1=new BasicStroke(axisWidth,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND);
        Graphics graphics = graph_screen.getGraphics();
        Graphics2D g2D = (Graphics2D) graphics;
        g2D.setColor(axisColor);
        g2D.setStroke(Stroke1);
        //Horizontal Bars
        int y;
        double yRange=yMaximum-yMinimum;        
        y=(int)Math.round(height-(height*(0.0-yMinimum)/yRange));
        graphics.drawLine(0,y,length,y);
        //Vertical bars
        int x;
        double xRange=xMaximum-xMinimum;        
        x=(int)Math.round((length*(0.0-xMinimum)/xRange));
        graphics.drawLine(x,0,x,height);
        }
    }

    private void drawGrid()
    {
        if (Grid){
        int length=graph_screen.getWidth();
        int height=graph_screen.getHeight();
        Graphics graphics = graph_screen.getGraphics();
        Graphics2D g2D = (Graphics2D) graphics;
        BasicStroke Stroke1=new BasicStroke(gridWidth,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND);
        g2D.setStroke(Stroke1);
        g2D.setColor(gridColor);
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
        //Vertical bars
        int x;
        double xRange=xMaximum-xMinimum;        
        int xminInt=(int)Math.round(xMinimum);
        int xmaxInt=(int)Math.round(xMaximum);
        for(int i=xminInt;i<=xmaxInt;i+=Math.round((xRange/100)+.5))
        {
            x=(int)Math.round((length*(i-xMinimum)/xRange));
            graphics.drawLine(x,0,x,height);
        }
        //Horizontal Bars
        int y;
        double yRange=yMaximum-yMinimum;
        int yminInt=(int)Math.round(yMinimum);
        int ymaxInt=(int)Math.round(yMaximum);
        for(int i=yminInt;i<=ymaxInt;i+=Math.round((yRange/100)+.5))
        {
            y=(int)Math.round(height-(height*(i-yMinimum)/yRange));
            graphics.drawLine(0,y,length,y);
        }
        }
    }


    private void clear()
    {
        //refresh display
        int length=graph_screen.getWidth();
        display1.setText("");
        //refresh graph
        Graphics graphics = graph_screen.getGraphics();
        graphics.setColor(Color.white);
        graphics.fillRect(0,0,length,graph_screen.getHeight());
   }

    //Draw colors of all the expressions
    private void setColors(Color f,Color g,Color a,Color b,Color c,Color d,Color e)
    {
        
    }

    //Plot graph
    public void plot()
    {
        clearGraph();
        Color[] colors ={Color.red,Color.blue,Color.green,Color.orange,Color.cyan,Color.magenta,Color.pink};
        saveExpression();        
        for (int i=0;i<7;i++)
        {
            drawAxis();
            drawGrid();
            if(getCertainExpression(i).length()>0)
            graphExpression(getCertainExpression(i),colors[i]);
        }        
    }

    //Check if expression is valid, if not turn the text feild red until the expression makes sense
    private void checkExpression()
    {
        String Expression=display1.getText();
        boolean pass=true;
        for(int i=0;i<Expression.length();i++)
        {           
            if(!(Expression.charAt(i)==
                ' ' || Expression.charAt(i)==
                '0' || Expression.charAt(i)==
                '1' || Expression.charAt(i)==
                '2' || Expression.charAt(i)==
                '3' || Expression.charAt(i)==
                '4' || Expression.charAt(i)==
                '5' || Expression.charAt(i)==
                '6' || Expression.charAt(i)==
                '7' || Expression.charAt(i)==
                '8' || Expression.charAt(i)==
                '9' || Expression.charAt(i)==
                '.' || Expression.charAt(i)==
                's' || Expression.charAt(i)==
                'c' || Expression.charAt(i)==
                't' || Expression.charAt(i)==
                'l' || Expression.charAt(i)==
               '√' || Expression.charAt(i)==
                'a' || Expression.charAt(i)==
                'x' || Expression.charAt(i)==
                'π' || Expression.charAt(i)==
                'n' || Expression.charAt(i)==
                'g' || Expression.charAt(i)==
                'b' || Expression.charAt(i)==
                'i' || Expression.charAt(i)==
                '^' || Expression.charAt(i)==
                'e' || Expression.charAt(i)==
                'o' || Expression.charAt(i)==
                '(' || Expression.charAt(i)==
                ')' || Expression.charAt(i)==
                '+' || Expression.charAt(i)==
                '-' || Expression.charAt(i)==
                '/' || Expression.charAt(i)==
                '*')) {
                pass=false;
            }            
        }
        //disable graph button if expression makes no sense
        btnplot.setEnabled(pass);
        //color the text field based on expression
        if(!pass)
        {
            display1.setBackground(Color.red);
        }else{
            display1.setBackground(Color.white);
        }        
    }

    //Check to see if a number makes sense
    private boolean checkNumber(String Number)
    {
        boolean pass=false;
        for(int i=0;i<Number.length();i++)
        {
            switch(Number.charAt(i))
            {
               case ' ':
               case '0':
               case '1':
               case '2':
               case '3':
               case '4':
               case '5':
               case '6':
               case '7':
               case '8':
               case '9':
               case '.':
               case '-':
                   if(i==0)
                   {pass=true;}
                   break;
               default:
                   pass=false;
            }
        }
        return !expression.solve(Number,0.0).equals("Error")&&pass;
    }

    private void drawCoordinates(java.awt.event.MouseEvent evt)
    {
        int length=graph_screen.getWidth();
        int height=graph_screen.getHeight();
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
        double xRange=(xMaximum-xMinimum);double yRange=(yMaximum-yMinimum);
        Graphics2D g2D = (Graphics2D) graph_screen.getGraphics();
        //get mouse position
        int mouse_x = evt.getX();
        int mouse_y = evt.getY();
        //determine graph coordinates
        String graph_x=Double.toString(xMinimum+((1.0*mouse_x/length)*xRange));
        String graph_y=Double.toString(yMaximum-((1.0*mouse_y/height)*yRange));
        if(graph_x.indexOf('.')!=-1&&graph_x.length()>graph_x.indexOf('.')+3)
        graph_x=graph_x.substring(0,graph_x.indexOf('.')+3);
        if(graph_y.indexOf('.')!=-1&&graph_y.length()>graph_y.indexOf('.')+3)
        graph_y=graph_y.substring(0,graph_y.indexOf('.')+3);
        //draw coordinates
        g2D.setColor(graphColor);
        g2D.fillRect(1,1,coords.length()*6,14);
        coords="Coordinates: ("+graph_x+","+graph_y+")";
        g2D.fillRect(1,1,coords.length()*6,14);
        g2D.setColor(Color.black);
        //set font to that of a button, in this case the Radian radio button
    }
  
    private void zoom(java.awt.event.MouseWheelEvent evt)
    {
        isZooming = true;
        double zoomFactor = .2;
        int length=graph_screen.getWidth();
        int height=graph_screen.getHeight();
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
        int zoomx=evt.getX();int zoomy=evt.getY();
        double xRange=(xMaximum-xMinimum);double yRange=(yMaximum-yMinimum);
        int rotation = evt.getWheelRotation();
        double XmaxZoom=(-zoomFactor/length)*zoomx+zoomFactor;
        double XminZoom=Math.abs(XmaxZoom-zoomFactor);
        double YmaxZoom=(-zoomFactor/height)*zoomy+zoomFactor;
        double YminZoom=Math.abs(YmaxZoom-zoomFactor);
        //Zoom in/out
        if(rotation==-1)
        {
            yMinimum+=YmaxZoom*yRange;
            yMaximum-=YminZoom*yRange;
            xMinimum+=XminZoom*xRange;
            xMaximum-=XmaxZoom*xRange;            
        }else{
            //maximum zoom out range
            if(xRange<1999999*2&&yRange<1999999*2)
            {
            //maximum zoom in range
            if(xRange<=.04&&yRange<=.04)
            {
                xMinimum-=.02;
                xMaximum+=.02;
                yMinimum=.02;
                yMaximum+=.02;
            }
            yMinimum-=YmaxZoom*yRange;
            yMaximum+=YminZoom*yRange;
            xMinimum-=XminZoom*xRange;
            xMaximum+=XmaxZoom*xRange;
            }
        }
        //write to bounds text fields
        DecimalFormat DForm = new DecimalFormat("#.##");
        xMinimum=Double.valueOf(DForm.format(xMinimum));
       xMaximum=Double.valueOf(DForm.format(xMaximum));
        yMinimum=Double.valueOf(DForm.format(yMinimum));
        yMaximum=Double.valueOf(DForm.format(yMaximum));
        
        //plot the zoomed graph
        plot();
        isZooming = false;
    }

    private void translateGraph(java.awt.event.MouseEvent evt)
    {
        int length=graph_screen.getWidth();
        int height=graph_screen.getHeight();
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
        int y2=evt.getY();
        int x2=evt.getX();
        int dx=x2-x1;
        int dy=y2-y1;
        xMinimum=xminimumClicked-(1.0*dx/length)*(xMaximum-xMinimum);
        xMaximum=xmaximumClicked-(1.0*dx/length)*(xMaximum-xMinimum);
        yMinimum=yminimumClicked+(1.0*dy/height)*(yMaximum-yMinimum);
        yMaximum=ymaximumClicked+(1.0*dy/height)*(yMaximum-yMinimum);
        //write to bounds text fields
        DecimalFormat DForm = new DecimalFormat("#.##");
        xMinimum=Double.valueOf(DForm.format(xMinimum));
        xMaximum=Double.valueOf(DForm.format(xMaximum));
        yMinimum=Double.valueOf(DForm.format(yMinimum));
        yMaximum=Double.valueOf(DForm.format(yMaximum));
        plot();
    }

    //Make sure ymax>ymin and xmax>xmin
    private boolean checkWindowBounds()
    {
        xMinimum=Xmin;
        xMaximum=Xmax;
        yMinimum=Ymin;
        yMaximum=Ymax;
        return xMinimum<xMaximum&&yMinimum<yMaximum;
    }

    //Instance variables
    private G_Calculations expression = new G_Calculations();
    private double xMinimum,xMaximum,yMinimum,yMaximum,S,E,incrnt,xminimumClicked,xmaximumClicked,yminimumClicked,ymaximumClicked;
    private int mode,precision,x1,y1,graphWidth=2,axisWidth=2,gridWidth=1;
    private boolean Axis=true,Grid=true,isTranslating,isZooming,drawInstantly = true;
    private String fx="",gx="",hx="",ix="",jx="",kx="",lx="",coords="Coordinates: (0.00,0.00)";
    private Color //default colors
            bgColor = Color.white,
            graphColor = Color.white,
            axisColor = Color.black,
            gridColor = Color.gray;
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphPlotting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphPlotting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphPlotting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphPlotting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphPlotting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnabs;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnallclr;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btncosec;
    private javax.swing.JButton btncot;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnlb;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmult;
    private javax.swing.JButton btnpi;
    private javax.swing.JButton btnplot;
    private javax.swing.JButton btnpow;
    private javax.swing.JButton btnrb;
    private javax.swing.JButton btnroot;
    private javax.swing.JButton btnsec;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btnsub;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnx;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField display1;
    private javax.swing.JPanel graph_screen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
 private void labelcolor(JLabel label){
        label.setBackground(new java.awt.Color(53,162,107));
    }
    
    private void resetlabelcolor(JLabel label){
        label.setBackground(new java.awt.Color(54,70,78));
    }
    private void labelmenucolor(JLabel label){
        label.setForeground(new java.awt.Color(0,0,0));
    }
    
    private void resetlabelmenucolor(JLabel label){
        label.setForeground(new java.awt.Color(255,255,255));
    }
}