
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANKIT
 */
public class ScientificCalculation11 extends javax.swing.JFrame {

    /**
     * Creates new form ScientificCalculation
     */
    
    private double a;
    private double b; 
    private boolean zeros;
    private boolean dec;
    private boolean s;
    private byte ax;
    private boolean drd;
    private double mem;
    private double on;
    
    public ScientificCalculation11() {
        initComponents();
        
    }
    int x = 0;
    int aa = 0;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        btnbin = new javax.swing.JButton();
        btnhex = new javax.swing.JButton();
        btnoct = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnln = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        btnper = new javax.swing.JButton();
        btnroot = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        display1 = new javax.swing.JTextField();
        display2 = new javax.swing.JTextField();
        btn5 = new javax.swing.JButton();
        btnallclr = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        btnmult = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btndesi = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();
        btnsubt = new javax.swing.JButton();
        btnexp = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        btn10powx = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        btnexp1 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        btnexp2 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(255, 204, 0));
        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("x^2");
        jButton14.setBorder(new javax.swing.border.MatteBorder(null));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 350, 61, 51));

        jButton15.setBackground(new java.awt.Color(255, 204, 0));
        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("x^y");
        jButton15.setBorder(new javax.swing.border.MatteBorder(null));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 408, 61, 51));

        jButton21.setBackground(new java.awt.Color(255, 204, 0));
        jButton21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Sin");
        jButton21.setBorder(new javax.swing.border.MatteBorder(null));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 184, 65, 43));

        jButton22.setBackground(new java.awt.Color(255, 204, 0));
        jButton22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Cos");
        jButton22.setBorder(new javax.swing.border.MatteBorder(null));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 236, 65, 51));

        jButton23.setBackground(new java.awt.Color(255, 204, 0));
        jButton23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Tan");
        jButton23.setBorder(new javax.swing.border.MatteBorder(null));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 292, 65, 51));

        btnbin.setBackground(new java.awt.Color(255, 204, 0));
        btnbin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnbin.setForeground(new java.awt.Color(255, 255, 255));
        btnbin.setText("Bin");
        btnbin.setBorder(new javax.swing.border.MatteBorder(null));
        btnbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinActionPerformed(evt);
            }
        });
        jPanel1.add(btnbin, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 184, 65, 43));

        btnhex.setBackground(new java.awt.Color(255, 204, 0));
        btnhex.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnhex.setForeground(new java.awt.Color(255, 255, 255));
        btnhex.setText("Hex");
        btnhex.setBorder(new javax.swing.border.MatteBorder(null));
        btnhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhexActionPerformed(evt);
            }
        });
        jPanel1.add(btnhex, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 236, 65, 51));

        btnoct.setBackground(new java.awt.Color(255, 204, 0));
        btnoct.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnoct.setForeground(new java.awt.Color(255, 255, 255));
        btnoct.setText("Oct");
        btnoct.setBorder(new javax.swing.border.MatteBorder(null));
        btnoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoctActionPerformed(evt);
            }
        });
        jPanel1.add(btnoct, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 292, 65, 51));

        btnlog.setBackground(new java.awt.Color(255, 204, 0));
        btnlog.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnlog.setForeground(new java.awt.Color(255, 255, 255));
        btnlog.setText("Log");
        btnlog.setBorder(new javax.swing.border.MatteBorder(null));
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        jPanel1.add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 350, 65, 51));

        btnln.setBackground(new java.awt.Color(255, 204, 0));
        btnln.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnln.setForeground(new java.awt.Color(255, 255, 255));
        btnln.setText("ln");
        btnln.setBorder(new javax.swing.border.MatteBorder(null));
        btnln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlnActionPerformed(evt);
            }
        });
        jPanel1.add(btnln, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 350, 65, 51));

        jButton32.setBackground(new java.awt.Color(255, 204, 0));
        jButton32.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText(")");
        jButton32.setBorder(new javax.swing.border.MatteBorder(null));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 408, 65, 51));

        jButton34.setBackground(new java.awt.Color(255, 204, 0));
        jButton34.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("(");
        jButton34.setBorder(new javax.swing.border.MatteBorder(null));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 408, 65, 51));

        btnper.setBackground(new java.awt.Color(255, 204, 0));
        btnper.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnper.setForeground(new java.awt.Color(255, 255, 255));
        btnper.setText("%");
        btnper.setBorder(new javax.swing.border.MatteBorder(null));
        btnper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperActionPerformed(evt);
            }
        });
        jPanel1.add(btnper, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 184, 61, 43));

        btnroot.setBackground(new java.awt.Color(255, 204, 0));
        btnroot.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnroot.setForeground(new java.awt.Color(255, 255, 255));
        btnroot.setText("√");
        btnroot.setBorder(new javax.swing.border.MatteBorder(null));
        btnroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrootActionPerformed(evt);
            }
        });
        jPanel1.add(btnroot, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 236, 61, 51));

        jButton40.setBackground(new java.awt.Color(255, 204, 0));
        jButton40.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("1/x");
        jButton40.setBorder(new javax.swing.border.MatteBorder(null));
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 293, 60, 52));

        jButton36.setBackground(new java.awt.Color(255, 204, 0));
        jButton36.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("M+");
        jButton36.setBorder(new javax.swing.border.MatteBorder(null));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 294, 65, 51));

        jButton38.setBackground(new java.awt.Color(255, 204, 0));
        jButton38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("<html>\nSolve Linear<br>&nbsp;&nbsp;Equations\n<html>");
        jButton38.setBorder(new javax.swing.border.MatteBorder(null));
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 408, 135, 53));

        jButton41.setBackground(new java.awt.Color(255, 204, 0));
        jButton41.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("M");
        jButton41.setBorder(new javax.swing.border.MatteBorder(null));
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 186, 65, 43));

        jButton42.setBackground(new java.awt.Color(255, 204, 0));
        jButton42.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("M-");
        jButton42.setBorder(new javax.swing.border.MatteBorder(null));
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 238, 65, 51));

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(">> Simple Calculator");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(">> Scientific Calculator");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(">> Graph Plotting");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(">> History");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(">> Exit");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Project by : Ankit Kaushal");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("& Ankit Kumar Singh");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel15)
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 71, 0, 410));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-menu-30.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 0, 60, 50);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SCIENTIFIC CALCULATOR");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(150, 0, 380, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calci.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(570, 0, 70, 50);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 14, 960, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display1.setBackground(new java.awt.Color(0, 0, 0));
        display1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        display1.setForeground(new java.awt.Color(204, 204, 255));
        display1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display1.setBorder(null);
        jPanel3.add(display1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 900, 50));

        display2.setBackground(new java.awt.Color(0, 0, 0));
        display2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        display2.setForeground(new java.awt.Color(204, 204, 255));
        display2.setBorder(null);
        jPanel3.add(display2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 77, 940, -1));

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(new javax.swing.border.MatteBorder(null));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 293, 63, 52));

        btnallclr.setBackground(new java.awt.Color(51, 51, 51));
        btnallclr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnallclr.setForeground(new java.awt.Color(255, 255, 255));
        btnallclr.setText("AC");
        btnallclr.setBorder(new javax.swing.border.MatteBorder(null));
        btnallclr.setMaximumSize(new java.awt.Dimension(17, 31));
        btnallclr.setMinimumSize(new java.awt.Dimension(17, 31));
        btnallclr.setPreferredSize(new java.awt.Dimension(17, 31));
        btnallclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallclrActionPerformed(evt);
            }
        });
        jPanel1.add(btnallclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 184, 134, 43));

        btnequal.setBackground(new java.awt.Color(0, 255, 0));
        btnequal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnequal.setForeground(new java.awt.Color(255, 255, 255));
        btnequal.setText("=");
        btnequal.setBorder(new javax.swing.border.MatteBorder(null));
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });
        jPanel1.add(btnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 408, 77, 50));

        btnmult.setBackground(new java.awt.Color(255, 204, 0));
        btnmult.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnmult.setForeground(new java.awt.Color(255, 255, 255));
        btnmult.setText("X");
        btnmult.setBorder(new javax.swing.border.MatteBorder(null));
        btnmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultActionPerformed(evt);
            }
        });
        jPanel1.add(btnmult, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 236, 76, 51));

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(new javax.swing.border.MatteBorder(null));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 293, 63, 52));

        btndiv.setBackground(new java.awt.Color(255, 204, 0));
        btndiv.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndiv.setForeground(new java.awt.Color(255, 255, 255));
        btndiv.setText("/");
        btndiv.setBorder(new javax.swing.border.MatteBorder(null));
        btndiv.setMaximumSize(new java.awt.Dimension(17, 31));
        btndiv.setMinimumSize(new java.awt.Dimension(17, 31));
        btndiv.setPreferredSize(new java.awt.Dimension(17, 31));
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });
        jPanel1.add(btndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 184, 77, 43));

        btn0.setBackground(new java.awt.Color(51, 51, 51));
        btn0.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(new javax.swing.border.MatteBorder(null));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 408, 133, 52));

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(new javax.swing.border.MatteBorder(null));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 351, 63, 53));

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(new javax.swing.border.MatteBorder(null));
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 236, 62, 51));

        btndesi.setBackground(new java.awt.Color(51, 51, 51));
        btndesi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndesi.setForeground(new java.awt.Color(255, 255, 255));
        btndesi.setText(".");
        btndesi.setBorder(new javax.swing.border.MatteBorder(null));
        btndesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesiActionPerformed(evt);
            }
        });
        jPanel1.add(btndesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 408, 63, 53));

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(new javax.swing.border.MatteBorder(null));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 236, 63, 51));

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(new javax.swing.border.MatteBorder(null));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 352, 63, 51));

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(new javax.swing.border.MatteBorder(null));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 236, 63, 51));

        btnadd.setBackground(new java.awt.Color(255, 204, 0));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("+");
        btnadd.setBorder(new javax.swing.border.MatteBorder(null));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 351, 76, 53));

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(new javax.swing.border.MatteBorder(null));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 351, 63, 53));

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(new javax.swing.border.MatteBorder(null));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 293, 62, 52));

        btnclr.setBackground(new java.awt.Color(51, 51, 51));
        btnclr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnclr.setForeground(new java.awt.Color(255, 255, 255));
        btnclr.setText("DEL");
        btnclr.setBorder(new javax.swing.border.MatteBorder(null));
        btnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrActionPerformed(evt);
            }
        });
        jPanel1.add(btnclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 184, 62, 43));

        btnsubt.setBackground(new java.awt.Color(255, 204, 0));
        btnsubt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsubt.setForeground(new java.awt.Color(255, 255, 255));
        btnsubt.setText("-");
        btnsubt.setBorder(new javax.swing.border.MatteBorder(null));
        btnsubt.setMaximumSize(new java.awt.Dimension(17, 31));
        btnsubt.setPreferredSize(new java.awt.Dimension(17, 31));
        btnsubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubtActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubt, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 293, 77, 52));

        btnexp.setBackground(new java.awt.Color(255, 204, 0));
        btnexp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnexp.setForeground(new java.awt.Color(255, 255, 255));
        btnexp.setText("exp");
        btnexp.setBorder(new javax.swing.border.MatteBorder(null));
        btnexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpActionPerformed(evt);
            }
        });
        jPanel1.add(btnexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 350, 65, 51));

        jButton33.setBackground(new java.awt.Color(255, 204, 0));
        jButton33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("pi");
        jButton33.setBorder(new javax.swing.border.MatteBorder(null));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 236, 65, 51));

        jButton35.setBackground(new java.awt.Color(255, 204, 0));
        jButton35.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("e");
        jButton35.setBorder(new javax.swing.border.MatteBorder(null));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 65, 49));

        btn10powx.setBackground(new java.awt.Color(255, 204, 0));
        btn10powx.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn10powx.setForeground(new java.awt.Color(255, 255, 255));
        btn10powx.setText("10^x");
        btn10powx.setBorder(new javax.swing.border.MatteBorder(null));
        btn10powx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10powxActionPerformed(evt);
            }
        });
        jPanel1.add(btn10powx, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 292, 65, 51));

        jButton37.setBackground(new java.awt.Color(255, 204, 0));
        jButton37.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("abs");
        jButton37.setBorder(new javax.swing.border.MatteBorder(null));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 184, 65, 43));

        jButton43.setBackground(new java.awt.Color(255, 204, 0));
        jButton43.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("!");
        jButton43.setBorder(new javax.swing.border.MatteBorder(null));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 294, 65, 51));

        jButton44.setBackground(new java.awt.Color(255, 204, 0));
        jButton44.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("nPr");
        jButton44.setBorder(new javax.swing.border.MatteBorder(null));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 186, 65, 43));

        jButton45.setBackground(new java.awt.Color(255, 204, 0));
        jButton45.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setText("nCr");
        jButton45.setBorder(new javax.swing.border.MatteBorder(null));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 238, 65, 51));

        btnexp1.setBackground(new java.awt.Color(255, 204, 0));
        btnexp1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnexp1.setForeground(new java.awt.Color(255, 255, 255));
        btnexp1.setText("a^b/c");
        btnexp1.setBorder(new javax.swing.border.MatteBorder(null));
        btnexp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnexp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 350, 65, 51));

        jButton46.setBackground(new java.awt.Color(255, 204, 0));
        jButton46.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("not");
        jButton46.setBorder(new javax.swing.border.MatteBorder(null));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 294, 65, 51));

        jButton47.setBackground(new java.awt.Color(255, 204, 0));
        jButton47.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("and");
        jButton47.setBorder(new javax.swing.border.MatteBorder(null));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 186, 65, 43));

        jButton48.setBackground(new java.awt.Color(255, 204, 0));
        jButton48.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("or");
        jButton48.setBorder(new javax.swing.border.MatteBorder(null));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 238, 65, 51));

        btnexp2.setBackground(new java.awt.Color(255, 204, 0));
        btnexp2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnexp2.setForeground(new java.awt.Color(255, 255, 255));
        btnexp2.setText("xor");
        btnexp2.setBorder(new javax.swing.border.MatteBorder(null));
        btnexp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexp2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnexp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 350, 65, 51));

        jButton49.setBackground(new java.awt.Color(255, 204, 0));
        jButton49.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("Less");
        jButton49.setBorder(new javax.swing.border.MatteBorder(null));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 408, 135, 53));

        jButton39.setBackground(new java.awt.Color(255, 204, 0));
        jButton39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("Inch to Foot");
        jButton39.setBorder(new javax.swing.border.MatteBorder(null));
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 348, 137, 53));

        jButton50.setBackground(new java.awt.Color(255, 204, 0));
        jButton50.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton50.setForeground(new java.awt.Color(255, 255, 255));
        jButton50.setText("Foot to Inch");
        jButton50.setBorder(new javax.swing.border.MatteBorder(null));
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 408, 137, 53));

        jButton51.setBackground(new java.awt.Color(255, 204, 0));
        jButton51.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 255, 255));
        jButton51.setText("<html>Celsius to <br>&nbsp;&nbsp;Kelvin <html>");
        jButton51.setBorder(new javax.swing.border.MatteBorder(null));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 137, 50));

        jButton52.setBackground(new java.awt.Color(255, 204, 0));
        jButton52.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton52.setForeground(new java.awt.Color(255, 255, 255));
        jButton52.setText("BACK");
        jButton52.setBorder(new javax.swing.border.MatteBorder(null));
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 137, 40));

        jButton54.setBackground(new java.awt.Color(255, 204, 0));
        jButton54.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 255, 255));
        jButton54.setText("<html> &nbsp;Celsius to <br>Fahrenheit <html>");
        jButton54.setBorder(new javax.swing.border.MatteBorder(null));
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 293, 137, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1020, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int fact(int n)
    {
    int i,f=1;
    for(i=1;i<=n;i++)
     {
         f=f*i;
     } 
     return f;
    }
    
    
    
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void btnbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinActionPerformed
   
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbinActionPerformed

    private void btnhexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhexActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhexActionPerformed

    private void btnoctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoctActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnoctActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlnActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlnActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void btn10powxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10powxActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10powxActionPerformed

    private void btnrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrootActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrootActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void btnperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnperActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        char []var = {'x', 'y', 'z', 'w'};
        //System.out.println("Enter the number of variables in the equations: ");
        int n = Integer.parseInt(JOptionPane.showInputDialog("Enter the number of variables in the equations:"));
        //System.out.println("Enter the coefficients of each variable for each equations");
        //System.out.println("ax + by + cz + ... = d");
        double [][]mat = new double[n][n];
        double [][]constants = new double[n][1];
        //input
        for(int i=0; i<n; i++)
        {
            for(int j=0; j<n; j++)
            {
                
                mat[i][j] = Double.parseDouble(JOptionPane.showInputDialog("Enter coefficient of "+(j+1)+" variable of "+(i+1)+" Equation"));
            }
            constants[i][0] = Double.parseDouble(JOptionPane.showInputDialog("Enter constant of "+(i+1)+" Equation"));
        }
        //Matrix representation
        /*for(int i=0; i<n; i++)
        {
            for(int j=0; j<n; j++)
            {
                System.out.print(" "+mat[i][j]);
            }
            System.out.print("  "+ var[i]);
            System.out.print("  =  "+ constants[i][0]);
            System.out.println();
        }*/
        //inverse of matrix mat[][]
        double inverted_mat[][] = invert(mat);
        /*System.out.println("The inverse is: ");
        for (int i=0; i<n; ++i) 
        {
            for (int j=0; j<n; ++j)
            {
                System.out.print(inverted_mat[i][j]+"  ");
            }
            System.out.println();
        }*/
        //Multiplication of mat inverse and constants
        double result[][] = new double[n][1];
        for (int i = 0; i < n; i++) 
        {
            for (int j = 0; j < 1; j++) 
            {
                for (int k = 0; k < n; k++)
                {	 
                    result[i][j] = result[i][j] + inverted_mat[i][k] * constants[k][j];
                }
            }
        }
        //display2.setText("The product is:");
        for(int i=0; i<n; i++)
        {
            JOptionPane.showMessageDialog(null,"Solution of "+(i+1)+" varable  :  "+result[i][0]);
        }
        
 
    }
 
    public static double[][] invert(double a[][]) 
    {
        int n = a.length;
        double x[][] = new double[n][n];
        double b[][] = new double[n][n];
        int index[] = new int[n];
        for (int i=0; i<n; ++i) 
            b[i][i] = 1;
 
 // Transform the matrix into an upper triangle
        gaussian(a, index);
 
 // Update the matrix b[i][j] with the ratios stored
        for (int i=0; i<n-1; ++i)
            for (int j=i+1; j<n; ++j)
                for (int k=0; k<n; ++k)
                    b[index[j]][k]
                    	    -= a[index[j]][i]*b[index[i]][k];
 
 // Perform backward substitutions
        for (int i=0; i<n; ++i) 
        {
            x[n-1][i] = b[index[n-1]][i]/a[index[n-1]][n-1];
            for (int j=n-2; j>=0; --j) 
            {
                x[j][i] = b[index[j]][i];
                for (int k=j+1; k<n; ++k) 
                {
                    x[j][i] -= a[index[j]][k]*x[k][i];
                }
                x[j][i] /= a[index[j]][j];
            }
        }
        return x;
    }
 
// Method to carry out the partial-pivoting Gaussian
// elimination.  Here index[] stores pivoting order.
 
    public static void gaussian(double a[][], int index[]) 
    {
        int n = index.length;
        double c[] = new double[n];
 
 // Initialize the index
        for (int i=0; i<n; ++i) 
            index[i] = i;
 
 // Find the rescaling factors, one from each row
        for (int i=0; i<n; ++i) 
        {
            double c1 = 0;
            for (int j=0; j<n; ++j) 
            {
                double c0 = Math.abs(a[i][j]);
                if (c0 > c1) c1 = c0;
            }
            c[i] = c1;
        }
 
 // Search the pivoting element from each column
        int k = 0;
        for (int j=0; j<n-1; ++j) 
        {
            double pi1 = 0;
            for (int i=j; i<n; ++i) 
            {
                double pi0 = Math.abs(a[index[i]][j]);
                pi0 /= c[index[i]];
                if (pi0 > pi1) 
                {
                    pi1 = pi0;
                    k = i;
                }
            }
 
   // Interchange rows according to the pivoting order
            int itmp = index[j];
            index[j] = index[k];
            index[k] = itmp;
            for (int i=j+1; i<n; ++i) 	
            {
                double pj = a[index[i]][j]/a[index[j]][j];
 
 // Record pivoting ratios below the diagonal
                a[index[i]][j] = pj;
 
 // Modify other elements accordingly
                for (int l=j+1; l<n; ++l)
                    a[index[i]][l] -= pj*a[index[j]][l];
            }
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if ( x == 210 ) {
            jPanel4.setSize(210, 440);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {

                        for ( int i = 210; i >= 0; i--){
                            Thread.sleep(1);
                            jPanel4.setSize(i, 440);

                            aa++;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        } else if( x == 0 ){
            jPanel4.setSize(x, 440);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            jPanel4.setSize(i, 440);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 210;
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        labelcolor(jLabel6);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        resetlabelcolor(jLabel6);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new GeneralCalculation().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        labelmenucolor(jLabel1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        resetlabelmenucolor(jLabel1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new ScientificCalculation().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        labelmenucolor(jLabel2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        resetlabelmenucolor(jLabel2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new GraphPlotting().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        labelmenucolor(jLabel3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        resetlabelmenucolor(jLabel3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new History().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        labelmenucolor(jLabel4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        resetlabelmenucolor(jLabel4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        labelmenucolor(jLabel5);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        resetlabelmenucolor(jLabel5);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"5");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btnallclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallclrActionPerformed
        display1.setText("");
        display2.setText(null);
        jRadioButton1.setSelected(true);
        zeros = false;
        dec = false;
        a = 0;
        b = 0;
        on= 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnallclrActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        b = Double.parseDouble(String.valueOf(display1.getText()));

        if(ax == 0){
            on = b;
            display2.setText(String.valueOf(b));
        }
        if(ax == 1){
            on = a + b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 2){
            on = a - b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 3){
            on = a * b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 4){
            on = a / b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 6){
            on = fact((int) a)/(fact((int) (a-b))*((fact((int) b))));
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 5){
            on = fact((int) a)/fact((int) (a-b));
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 7){
            on = (int)a&(int)b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 8){
            on = (int)a|(int)b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(ax == 9){
            on = (int)a^(int)b;
            display2.setText(display2.getText() + String.valueOf(b));
        }
        if(on > -100000000 && on < 100000000){
            display1.setText(String.valueOf(on));
        }
        else{
            display1.setText("Error");
        }

        String eq=display2.getText();

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
            //JOptionPane.showMessageDialog(this,"Added successfully");
        }
        catch (Exception e)
        { JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }

        a = 0;
        b = 0;
        ax = 0;

        ax = 0;
        dec = false;
        zeros = false;

        // TODO add your handling code here:
    }//GEN-LAST:event_btnequalActionPerformed

    private void btnmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultActionPerformed
        if(ax == 0){
            a = Double.parseDouble(String.valueOf(display1.getText()));
        }
        else{
            b = Double.parseDouble(String.valueOf(display1.getText()));
        }
        if(ax == 1){
            a = a + b;
        }
        if(ax == 2){
            a = a - b;
        }
        if(ax == 3){
            a = a * b;
        }
        if(ax == 4){
            a = a / b;
        }
        display1.setText("0");
        display2.setText(String.valueOf(a) + "x");
        ax = 3;
        dec = false;
        zeros = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmultActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"6");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        if(ax == 0){
            a = Double.parseDouble(String.valueOf(display1.getText()));
        }
        else{
            b = Double.parseDouble(String.valueOf(display1.getText()));
        }
        if(ax == 1){
            a = a + b;
        }
        if(ax == 2){
            a = a - b;
        }
        if(ax == 3){
            a = a * b;
        }
        if(ax == 4){
            a = a / b;
        }
        display1.setText("0");
        display2.setText(String.valueOf(a) + "/");
        ax = 4;
        dec = false;
        zeros = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_btndivActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"0");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"1");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"7");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btndesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesiActionPerformed
        if(!dec){
            display1.setText(display1.getText() + ".");
            dec = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btndesiActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"8");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"2");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"9");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if(ax == 0){
            a = Double.parseDouble(String.valueOf(display1.getText()));
        }
        else{
            b = Double.parseDouble(String.valueOf(display1.getText()));
        }
        if(ax == 1){
            a = a + b;
        }
        if(ax == 2){
            a = a - b;
        }
        if(ax == 3){
            a = a * b;
        }
        if(ax == 4){
            a = a / b;
        }
        display1.setText("0");
        display2.setText(String.valueOf(a) + "+");
        ax = 1;
        dec = false;
        zeros = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"3");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(!zeros && !dec){
            display1.setText(null);
        }
        display1.setText(display1.getText()+"4");
        zeros = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrActionPerformed
    display1.setText("0");
    zeros = false;
    dec = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrActionPerformed

    private void btnsubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubtActionPerformed
        if(ax == 0){
            a = Double.parseDouble(String.valueOf(display1.getText()));
        }
        else{
            b = Double.parseDouble(String.valueOf(display1.getText()));
        }
        if(ax == 1){
            a = a + b;
        }
        if(ax == 2){
            a = a - b;
        }
        if(ax == 3){
            a = a * b;
        }
        if(ax == 4){
            a = a / b;
        }
        display1.setText("0");
        display2.setText(String.valueOf(a) + "-");
        ax = 2;
        dec = false;
        zeros = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubtActionPerformed

    private void btnexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexpActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
    b = Double.parseDouble(String.valueOf(display1.getText()));
    
    int fact=1;
    for(int i=1;i<=b;i++){    
      fact=fact*i;    
    }
    on=fact;
        
    if(on > -100000000 && on < 100000000){
        display1.setText(String.valueOf(on));
    }
    else{
        display1.setText("Error"); 
    }
    display2.setText(String.valueOf(b) + "!");
    
    String eq=display2.getText();
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
        Statement stmt = con.createStatement();
        stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
        //JOptionPane.showMessageDialog(this,"Added successfully");
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error in Connectivity");
    }
    
    on = 0;
    ax = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
    a = Double.parseDouble(String.valueOf(display1.getText()));
    display1.setText("");
    display2.setText(String.valueOf(a) + "P");
        
    dec= false;
    zeros= false;
    ax = 5;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
    a = Double.parseDouble(String.valueOf(display1.getText()));
    display1.setText("");
    display2.setText(String.valueOf(a) + "C");
        
    dec= false;
    zeros= false;
    ax = 6;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void btnexp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexp1ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
    b = Double.parseDouble(String.valueOf(display1.getText()));
    on = ~(int)b;
        
    if(on > -100000000 && on < 100000000){
        display1.setText(String.valueOf(on));
    }
    else{
        display1.setText("Error"); 
    }
    display2.setText(String.valueOf(b) + "~");
    
    String eq=display2.getText();
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
        Statement stmt = con.createStatement();
        stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
        //JOptionPane.showMessageDialog(this,"Added successfully");
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error in Connectivity");
    }
    
    
    on = 0;
    ax = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
    a = Double.parseDouble(String.valueOf(display1.getText()));
    display1.setText("");
    display2.setText(String.valueOf(a) + "and");
        
    dec= false;
    zeros= false;
    ax = 7;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
    a = Double.parseDouble(String.valueOf(display1.getText()));
    display1.setText("");
    display2.setText(String.valueOf(a) + "or");
        
    dec= false;
    zeros= false;
    ax = 8;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton48ActionPerformed

    private void btnexp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexp2ActionPerformed
    a = Double.parseDouble(String.valueOf(display1.getText()));
    display1.setText("");
    display2.setText(String.valueOf(a) + "xor");
        
    dec= false;
    zeros= false;
    ax = 9;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexp2ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
    new ScientificCalculation().setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton49ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    btnper.setEnabled(false);
    btnroot.setEnabled(false);
    jButton40.setEnabled(false);
    jButton14.setEnabled(false);
    jButton15.setEnabled(false);
    jButton21.setEnabled(false);
    jButton22.setEnabled(false);
    jButton23.setEnabled(false);
    btnlog.setEnabled(false);
    jButton34.setEnabled(false);
    jButton32.setEnabled(false);
    btnbin.setEnabled(false);
    btnhex.setEnabled(false);
    btnoct.setEnabled(false);
    btnln.setEnabled(false);
    //btnpowx.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
    b = Double.parseDouble(String.valueOf(display1.getText()));
    on = b/12;
        
    if(on > -100000000 && on < 100000000){
        display1.setText(String.valueOf(on));
    }
    else{
        display1.setText("Error"); 
    }
    display2.setText(String.valueOf(b) + "inch");
    
    String eq=display2.getText();
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
        Statement stmt = con.createStatement();
        stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
        //JOptionPane.showMessageDialog(this,"Added successfully");
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error in Connectivity");
    }
    
    
    on = 0;
    ax = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
    b = Double.parseDouble(String.valueOf(display1.getText()));
    on = b*12;
        
    if(on > -100000000 && on < 100000000){
        display1.setText(String.valueOf(on));
    }
    else{
        display1.setText("Error"); 
    }
    display2.setText(String.valueOf(b) + "foot");
    
    String eq=display2.getText();
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
        Statement stmt = con.createStatement();
        stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
        //JOptionPane.showMessageDialog(this,"Added successfully");
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error in Connectivity");
    }
    
    
    on = 0;
    ax = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
    b = Double.parseDouble(String.valueOf(display1.getText()));
    on = b*12;
        
    if(on > -100000000 && on < 100000000){
        display1.setText(String.valueOf(on));
    }
    else{
        display1.setText("Error"); 
    }
    display2.setText(String.valueOf(b) + "C");
    
    String eq=display2.getText();
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
        Statement stmt = con.createStatement();
        stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
        //JOptionPane.showMessageDialog(this,"Added successfully");
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error in Connectivity");
    }
    
    
    on = 0;
    ax = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
    new ScientificCalculation().setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
    b = Double.parseDouble(String.valueOf(display1.getText()));
    on = (9.0/5.0)*b + 32;
        
    if(on > -100000000 && on < 100000000){
        display1.setText(String.valueOf(on));
    }
    else{
        display1.setText("Error"); 
    }
    display2.setText(String.valueOf(b) + "C");
    
    String eq=display2.getText();
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost/calculator","root","kaushal");
        Statement stmt = con.createStatement();
        stmt.executeUpdate("Insert into memory values('"+eq+"','"+on+"');");
        //JOptionPane.showMessageDialog(this,"Added successfully");
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error in Connectivity");
    }
    
    
    on = 0;
    ax = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton54ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10powx;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnallclr;
    private javax.swing.JButton btnbin;
    private javax.swing.JButton btnclr;
    private javax.swing.JButton btndesi;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnexp;
    private javax.swing.JButton btnexp1;
    private javax.swing.JButton btnexp2;
    private javax.swing.JButton btnhex;
    private javax.swing.JButton btnln;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmult;
    private javax.swing.JButton btnoct;
    private javax.swing.JButton btnper;
    private javax.swing.JButton btnroot;
    private javax.swing.JButton btnsubt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField display1;
    private javax.swing.JTextField display2;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton54;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label){
        label.setBackground(new java.awt.Color(53,162,107));
    }
    
    private void resetlabelcolor(JLabel label){
        label.setBackground(new java.awt.Color(54,70,78));
    }
    private void labelmenucolor(JLabel label){
        label.setForeground(new java.awt.Color(0,0,0));
    }
    
    private void resetlabelmenucolor(JLabel label){
        label.setForeground(new java.awt.Color(255,255,255));
    }
}
